# Basic information
# ----------------------------
title: Protesilaos Stavrou
email: public@protesilaos.com
author: Protesilaos Stavrou
description: ""
url: "https://protesilaos.com"
baseurl: ""
timezone: "Athens/Europe"
date_format: "%Y-%m-%d"
logo: "/assets/images/brand/protesilaos-logo.png"

# Collections
# ----------------------------

# define collections
collections:
  news:
    output: true
  archive:
    output: true
  archive-codelog:
    output: true
  commentary:
    output: true
  books:
    output: true
  codelog:
    output: true
  jokes:
    output: true
  life:
    output: true
  greek:
    output: true
  pages:
    output: true
  politics:
    output: true
  seminars:
    output: true
  interpretations:
    output: true
  poems:
    output: true

# collection defaults
# `group` is used by the `nextprev.html` module (_includes)
# `image` defines a fallback for social media img metadata
# `index` sets the base URL slug
# `master` refers to the catch-all XML feed
defaults:
  - scope:
      type: news
    values:
      layout: post
      index: "/news/"
      group: News and Announcements
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: archive
    values:
      layout: archive
      index: "/blog-archive/"
      group: Blog archive entries
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: archive-codelog
    values:
      layout: archive
      index: "/codelog-archive/"
      group: Code blog archive entries
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: commentary
    values:
      layout: post
      index: "/commentary/"
      group: Entries on general life isssues
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: books
    values:
      layout: post
      index: "/books/"
      group: "Books and standalone publications"
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: codelog
    values:
      layout: post
      index: "/codelog/"
      group: Code blog entries
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: jokes
    values:
      layout: elpost
      index: "/jokes/"
      group: Ατάκες και αστειϊσμοί
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: life
    values:
      layout: elpost
      index: "/life/"
      group: Σημειώσεις περί της απλής ζωής
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: greek
    values:
      layout: elpost
      index: "/greek/"
      group: Αναρτήσεις πολιτικής
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: pages
    values:
      layout: page
      image: "/assets/images/brand/protesilaos-logo.png"
      master: false
  - scope:
      type: politics
    values:
      layout: post
      index: "/politics/"
      group: Political writings
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: seminars
    values:
      layout: seminar
      index: "/seminars/"
      group: Seminar episodes
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: interpretations
    values:
      layout: post
      index: "/interpretations/"
      group: Interpretations and critiques
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true
  - scope:
      type: poems
    values:
      layout: poem
      index: "/poems/"
      group: Poems
      image: "/assets/images/brand/protesilaos-logo.png"
      master: true


# Plugins and settings
# ----------------------------

# plugin list
# also see Gemfile (though docs seem to suggest either of)
# install with `bundle install`
# update with `bundle update`
plugins:
  - jekyll
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

# social SEO
social:
  name: Protesilaos Stavrou
  links:
    - https://github.com/protesilaos
    - https://gitlab.com/protesilaos
    - https://www.youtube.com/@protesilaos
    - https://soundcloud.com/protesilaos

# Where things are
# ----------------------------
source:       .
destination:  _site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes

# Build settings
# ----------------------------
permalink: /:collection/:name/

# build output
# NOTE commented these out because of build failures
# liquid:
  # error_mode: strict
  # strict_filters: true
  # strict_variables: true
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: false
  footnote_backlink: '[^]'
  hard_wrap: false
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   disable : true # disable syntax highlighting

# server defaults
detach: false
port: 4000
host: 127.0.0.1
show_dir_listing: false

# exclude from builds
# see `_config-dev.yml' for a complete list
# call that file in development with:
# bundle exec jekyll serve --config _config.yml,_config-dev.yml
exclude:
  - README.md
  - Gemfile
  - vendor
  - dev
  - _src
